name: CI

on:
  push:
    branches:
      - api-testing
    paths:
      - tests/api-testing

  pull_request:
    branches:
      - main
    paths:
      - tests/api-testing
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.12.1'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
